DROP TABLE EMAILS;
CREATE TABLE EMAILS (
	EMAIL varchar(100),
    LANDING_PAGE_ID varchar(1000),
    SUBSCRIBE_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (EMAIL, LANDING_PAGE_ID),
    FOREIGN KEY (LANDING_PAGE_ID) REFERENCES LANDING_PAGES (ID)
);

INSERT INTO EMAILS VALUES ("nerds@moolah.com", "-1", NOW());
INSERT INTO EMAILS VALUES ("kids@greenlight.com", "-2", NOW());

SELECT * FROM EMAILS;