CREATE TABLE MULTIPLE_CHOICE_QUESTIONS (
	ID INTEGER NOT NULL PRIMARY KEY,
    LANDING_PAGE_ID varchar(100),
    QUESTION varchar(1000)
);

CREATE TABLE MULTIPLE_CHOICE_ANSWERS (
	ID INTEGER NOT NULL PRIMARY KEY,
    QUESTION_ID INTEGER,
    ANSWER_TEXT varchar(1000)
);

INSERT INTO MULTIPLE_CHOICE_QUESTIONS VALUES (-1, -1, "Do you think we are cool");
INSERT INTO MULTIPLE_CHOICE_ANSWERS VALUES (-1, -1, "Yes");
INSERT INTO MULTIPLE_CHOICE_ANSWERS VALUES (-2, -1, "No");
